[project]
name = "lab1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "willian-MAS", email = "willian.pads26@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "juscraper>=0.1.5",
    "pandas>=3.0.5",
    "plotnine>=0.15.8",
]

[project.scripts]
lab1 = "lab1:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
